api_platform:
  formats:
    json: [ 'application/json' ]
    jsonld: [ 'application/ld+json' ]
    html: [ 'text/html' ]
    multipart: [ 'multipart/form-data' ]
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
  defaults:
    pagination_client_items_per_page: true
    collection:
      pagination:
        items_per_page_parameter_name: itemsPerPage # Default value
