# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    csrf_protection: true
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: true
        cookie_samesite: lax
        cookie_httponly: true
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true
when@test:
    framework:
        cors: true
        logger: { enabled: true }
        serializer: { enable_annotations: true }

        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

    router:
        # ...
        resource: '%kernel.project_dir%/config/routes.yaml'