liip_imagine:

    driver: "gd"
    webp:
        generate: true
    default_filter_set_settings:
        format: webp
    resolvers:
        default:
            web_path: ~
    controller:
        redirect_response_code: 302
    filter_sets:
        thumbnail_web_path:
            format: webp
            quality: 100
            filters:
                thumbnail:
                    size: [330, 223]
                    mode: outbound
