# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        images_upload:
            uri_prefix: /public/uploads
            upload_destination: "%kernel.project_dir%/public/uploads"
            namer: Vich\UploaderBundle\Naming\OrignameNamer